<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Vinamr Sachdeva">
<meta name="dcterms.date" content="2022-12-12">

<title>Vinamr Sachdeva - Estimating potential rent proceeds from government-owned land parcels in Delhi</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Vinamr Sachdeva</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/vinamrsachdeva" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/vinamrsachdeva" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://old.reddit.com/u/vinamrsachdeva" rel="" target=""><i class="bi bi-reddit" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Estimating potential rent proceeds from government-owned land parcels in Delhi</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">georgism</div>
                <div class="quarto-category">land</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Vinamr Sachdeva </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">December 12, 2022</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#vacant-land-parcels-under-delhi-development-authority-dda" id="toc-vacant-land-parcels-under-delhi-development-authority-dda" class="nav-link active" data-scroll-target="#vacant-land-parcels-under-delhi-development-authority-dda"><span class="header-section-number">1</span> Vacant land parcels under Delhi Development Authority (DDA)</a></li>
  <li><a href="#under-utilized-lutyens-bungalow-zone" id="toc-under-utilized-lutyens-bungalow-zone" class="nav-link" data-scroll-target="#under-utilized-lutyens-bungalow-zone"><span class="header-section-number">2</span> Under-utilized Lutyens Bungalow Zone</a></li>
  <li><a href="#the-cheap-leashold-of-igi-airport" id="toc-the-cheap-leashold-of-igi-airport" class="nav-link" data-scroll-target="#the-cheap-leashold-of-igi-airport"><span class="header-section-number">3</span> The cheap leashold of IGI Airport</a></li>
  <li><a href="#the-rent-free-jawaharlal-nehru-university" id="toc-the-rent-free-jawaharlal-nehru-university" class="nav-link" data-scroll-target="#the-rent-free-jawaharlal-nehru-university"><span class="header-section-number">4</span> The rent-free Jawaharlal Nehru University</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p>In a <a href="https://vinamrsachdeva.github.io/2022/04/07/surplus-public-land.html">previous post</a>, I tried to make sense of an estimate of the surplus land owned by the Indian government. The research I did for that post introduced me to the reality that there are several thousand acres of government-owned land parcels in my hometown, Delhi, that are either vacant or under-utilized or on an extremely cheap leasehold. These can be rented and the rent proceeds could be provided directly to the either the people of Delhi or the whole of India. I won’t get into whether we should be collecting rent from these selected land parcels or who should get the rent proceeds as of now, I might tackle those questions in a separate post later. In this post, I’m going to provide a high confidence lower bound figure for what the rent proceeds could be from land parcels in the city of Delhi.</p>
<p>I found 4 main entities which own large swaths of land that was vacant or under-utilized or was on an extremely cheap leasehold in Delhi (~5.7% of the entire land area of Delhi) which could be potentially leased:</p>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Current status</th>
<th>Area (acres)</th>
<th>Area (sq km)</th>
<th>Annual Rent (in Rs. crore)</th>
<th>Annual Rent per Indian voter (in Rs.)</th>
<th>Annual Rent per Delhi voter (in Rs.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Delhi Development Authority</td>
<td>Vacant</td>
<td>8683</td>
<td>35</td>
<td>2175</td>
<td>22</td>
<td>1500</td>
</tr>
<tr class="even">
<td>Lutyens Bungalow Zone</td>
<td>Sub-optimal rent collection, sub-optimal density</td>
<td>6170</td>
<td>25</td>
<td>38,640</td>
<td>386</td>
<td>26648</td>
</tr>
<tr class="odd">
<td>Indira Gandhi International Airport</td>
<td>Sub-optimal rent collection</td>
<td>4800</td>
<td>19</td>
<td>2,717</td>
<td>27</td>
<td>1874</td>
</tr>
<tr class="even">
<td>Jawaharlal Nehru University</td>
<td>Sub-optimal (0) rent collection</td>
<td>1000</td>
<td>4</td>
<td>1,618</td>
<td>16</td>
<td>1116</td>
</tr>
<tr class="odd">
<td>Total</td>
<td></td>
<td>20653</td>
<td>83</td>
<td>45,150</td>
<td>451.5</td>
<td>31138</td>
</tr>
</tbody>
</table>
<p>There was also a fifth entity, namely the Gram Sabha, but since <a href="https://timesofindia.indiatimes.com/city/delhi/boost-to-housing-as-dda-gets-gram-sabha-land/articleshow/67823528.cms">a significant chunk of Gram Sabha land has been given to DDA</a>, I decided to leave it for this post considering the uncertainity of whether I would have already included that in my estimation for the vacant parcels under DDA.</p>
<section id="vacant-land-parcels-under-delhi-development-authority-dda" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="vacant-land-parcels-under-delhi-development-authority-dda"><span class="header-section-number">1</span> Vacant land parcels under Delhi Development Authority (DDA)</h2>
<blockquote class="blockquote">
<p>The Delhi Development Authority (DDA) was established in the year 1957 under the provision of the Delhi Development Act,1957 to foster the development of New Delhi. DDA is controlled by the Union Ministry of Urban Development.</p>
<p>DDA handles housing, infrastructure, commercial properties, land development, and sports complexes of the city. It acquires vast tracts of land for commercial, industrial, residential, and recreational purposes.</p>
<p>A survey was conducted in 2014 with the help of National Productivity Council and Geospatial Data Limited regarding DDA administered land in the city. It revealed that around 5,500 acres of land under DDA was lying vacant across the city.<a href="https://wiki.dhanvapasi.com/index.php/Delhi_Development_Authority#cite_note-1">[1]</a> This comes to around 85 per cent of the area of Lutyens Bungalow Zone and around 50 per cent of the total land area of New Delhi.<br>
The focus of the survey was to protect these plots from illegal encroachment. The survey also found that 298 acres of land under DDA was under litigation. However, there can be a possibility that DDA holds more such land parcels in the city which are kept unused and are locked by the organization.<br>
These unused land parcels create an artificial scarcity of land in the city which imposes a cost on everyone. It results in an increase in the cost of land due to which the cost of infrastructure projects also increases. Freeing up all such unused and locked land parcels have the potential of reducing the artificial scarcity of land in the city.</p>
<p><strong>Details of Vacant Land Under DDA</strong></p>
<img src="https://substackcdn.com/image/fetch/w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2Faa37966f-484a-421a-b578-e82a9c5a644a_992x744.png" title="https://wiki.dhanvapasi.com/images/2/21/DDA.png" class="img-fluid" alt="https://wiki.dhanvapasi.com/images/2/21/DDA.png">
<p><img src="https://substackcdn.com/image/fetch/w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F06e973c2-37e4-4e44-b89a-b7187198dcf1_1232x526.png" class="img-fluid"></p>
<p>The total value of vacant land held under the DDA is about ₹ 11,481 crore. This value is computed using a conservative price of ₹ 4,71,600 with a meagre FSI of just 1. Refer to the map and accompanying table for details.<br>
Experts have estimated the value of these unused land parcels to be around ₹ 1 lakh crore.<a href="https://wiki.dhanvapasi.com/index.php/Delhi_Development_Authority#cite_note-3">[3]</a>. If these large chunks of unused land are monetized then each Indian household may set to gain atleast ₹ 459.</p>
<h4 id="references" data-number="1.0.1" class="anchored"><span class="header-section-number">1.0.1</span> References</h4>
<ol type="1">
<li><p><a href="https://timesofindia.indiatimes.com/city/delhi/DDA-reports-5484-acres-of-vacant-land/articleshow/45052865.cms" class="uri">https://timesofindia.indiatimes.com/city/delhi/DDA-reports-5484-acres-of-vacant-land/articleshow/45052865.cms</a></p></li>
<li><p>Delhi Development Authority, [“DDA”]</p></li>
<li><p><a href="https://timesofindia.indiatimes.com/city/delhi/DDA-sitting-on-Delhi-land-worth-Rs-1-lakh-crore/articleshow/45172286.cms" class="uri">https://timesofindia.indiatimes.com/city/delhi/DDA-sitting-on-Delhi-land-worth-Rs-1-lakh-crore/articleshow/45172286.cms</a></p></li>
</ol>
</blockquote>
<p><a href="https://wiki.dhanvapasi.com/index.php/Delhi_Development_Authority">source</a></p>
<p>First of all, the numbers in the wiki’s table and the rest of their text don’t addup. For example, they say they have used a rate of “Rs. 4,71,600” but don’t mention for how much land. If we go by their source [3], we can read that DDA’s then vice-chairman said:</p>
<blockquote class="blockquote">
<p>This is for the first time in DDA’s history that the whole inventory of land, whose worth we estimate to be more than Rs 1 lakh crore, has been compiled and put in the public domain. […]</p>
</blockquote>
<p>This is more than 9 times of what they estimate.</p>
<p>If we use DDA’s estimate for the value of the land (which I think they might have estimated using the circle rate), then the rate comes out close to Rs. 43,500 per square meter. This means that these parcels are located mainly in the localities in the <a href="https://www.magicbricks.com/blog/circle-rates-in-delhi/118402.html">circle-rate categories F, G and H</a>. (It is common knowledge that the circle rate <a href="https://www.thehindubusinessline.com/opinion/the-official-price-of-land-is-a-joke/article64592464.ece">highly underestimates the sale price of land</a> and if the land is auctioned, I won’t be surprised if they go for Rs. 1-2 lakh per square meter given larger parcels are divided into smaller ones so as to lower the entry barrier in the auction.)</p>
<p>Secondly, since then, I think the DDA has updated their list of vacant land parcels that it owns, which you can download from <a href="https://dda.gov.in/sites/default/files/Landmgmt/Vacant_Land_parcels.pdf">here (click)</a>. I say this because my estimate using their list is different (more) than what the wiki says. I have calculated the total number of parcels and their total area by land use in <em>Sheet1</em> of <a href="https://docs.google.com/spreadsheets/d/1XMgYRKLkVaEaEy_Yj43tdn3VtFRqC7qN/edit?usp=sharing&amp;ouid=111921907653919850843&amp;rtpof=true&amp;sd=true">this spreadsheet</a>. I couldn’t get accurate numbers due to errors in formatting and incomplete information provided in DDA’s list, for example, some parcels had unknown land-use, some has their area in unknown units, etc. But these numbers can, at least, be considered lower bounds.</p>
<p>DDA owns a total of 4,255 vacant parcels, whose total area is <em>at least</em> 8,683 acres. This is equivalent of ~35 square kilometers or ~2.4% of the total land area of Delhi. These parcels are categorized for different land use <em>roughly</em> in the following manner:</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Land-use</th>
<th>No.&nbsp;of plots</th>
<th>Area (in acres)</th>
<th>Area (in sq m)</th>
<th>Area (in sq ft)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Residential</td>
<td>1534</td>
<td>2904</td>
<td>11752942.32</td>
<td>126498240</td>
</tr>
<tr class="even">
<td>Commercial</td>
<td>333</td>
<td>1810</td>
<td>7326796.22</td>
<td>78843600</td>
</tr>
<tr class="odd">
<td>Industrial</td>
<td>405</td>
<td>591</td>
<td>2391761.62</td>
<td>25743960</td>
</tr>
<tr class="even">
<td>Not known</td>
<td>208</td>
<td>273</td>
<td>1105359.607</td>
<td>11891880</td>
</tr>
<tr class="odd">
<td>PSP</td>
<td>245</td>
<td>588</td>
<td>2378708.544</td>
<td>25613280</td>
</tr>
<tr class="even">
<td><strong>Residential + Commercial + Industrial + Not known + PSP</strong></td>
<td><strong>2725</strong></td>
<td><strong>6166</strong></td>
<td><strong>24955568.31</strong></td>
<td><strong>268590960</strong></td>
</tr>
<tr class="odd">
<td>[Blank]</td>
<td>503</td>
<td>265</td>
<td>1072132</td>
<td>11543400</td>
</tr>
<tr class="even">
<td>Community Facilities</td>
<td>6</td>
<td>22</td>
<td>88300</td>
<td>958320</td>
</tr>
<tr class="odd">
<td>Transport</td>
<td>31</td>
<td>59</td>
<td>236823.63</td>
<td>2570040</td>
</tr>
<tr class="even">
<td>Utility</td>
<td>7</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Recreational</td>
<td>36</td>
<td>515</td>
<td>2085443</td>
<td>22433400</td>
</tr>
<tr class="even">
<td>Mutli-level parking</td>
<td>1</td>
<td>2</td>
<td>8040</td>
<td>87120</td>
</tr>
<tr class="odd">
<td>Green</td>
<td>633</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><strong>Total identified</strong></td>
<td><strong>3308</strong></td>
<td><strong>7029</strong></td>
<td><strong>28446306.94</strong></td>
<td><strong>306183240</strong></td>
</tr>
<tr class="odd">
<td>Others</td>
<td>917</td>
<td>1654</td>
<td>6692924.232</td>
<td>72048240</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td><strong>4225</strong></td>
<td><strong>8683</strong></td>
<td><strong>35139231.18</strong></td>
<td><strong>378231480</strong></td>
</tr>
</tbody>
</table>
<p><em>Table: All of the land in the ‘Others’ category belongs to some Land-use category but had to be kept in a different bin due to formatting errors in DDA’s list.</em></p>
<p>It is also important to note that DDA is ready to re-define land use based on current needs as their then vice-chairman has <a href="https://timesofindia.indiatimes.com/city/delhi/DDA-sitting-on-Delhi-land-worth-Rs-1-lakh-crore/articleshow/45172286.cms">clarified</a>:</p>
<blockquote class="blockquote">
<p>Also we are looking to redefine land uses. The land use was earmarked a long time ago. Based on current needs, we may change industrial land to residential.</p>
</blockquote>
<p>Residential, commercial, industrial, “not known” and PSP (i.e.&nbsp;Public and Semi-public facilities), sums up to ~2.5 crore square meters.</p>
<p>If we consider the circle rate of Rs. 43,500 per square meter and a rent rate (<a href="https://en.wikipedia.org/wiki/Capitalization_rate">cap rate</a>) of 2%, the rent proceeds from all this land will be ~Rs. 2,175 crore per year. (This checks with the valuation of the vice-chairmain since 2% of Rs. 1 lakh crore is Rs. 2,000 crore.) If this rent is distributed amongst all adult citizens (for the purpose of this post, I’m defining adult citizens as registered voters) of India, then each will receive ~Rs. 22 per year; if it is distributed amongst all adult citizens of Delhi, then each will receive ~Rs. 1,500 per year.</p>
<p>For context, if we consider <a href="https://en.wikipedia.org/wiki/Floor_area_ratio">FSI</a> of 3 for residential buildings, then DDA is sitting on vacant land that can provide a built-up area of ~38 crore square feet. This is equivalent of ~3.8 lakh, 1,000 square feet flats. This is more than 10 times the <a href="https://www.statista.com/statistics/1203739/india-residential-unit-sales-delhi-ncr/">annual housing unit sales of the entire Delhi NCR</a> (not just Delhi). This means that it is possible that the real estate market will crash if all of this land is leased and so the rent collected might be less. Later, once this artificial land scarcity is reduced, productivity might increase and land prices might increase. Irrespective of whether land prices are higher or lower than what they are at now, people will be better off either via the rental income they will get or via lower land prices.</p>
</section>
<section id="under-utilized-lutyens-bungalow-zone" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="under-utilized-lutyens-bungalow-zone"><span class="header-section-number">2</span> Under-utilized Lutyens Bungalow Zone</h2>
<blockquote class="blockquote">
<p>The Lutyens Bungalow Zone (LBZ) is the most valuable parcel of real estate in the country. Located in the heart of Delhi it comprises of 3,000 government properties and 600 private bungalows.<br>
<strong>The land parcel is actively kept out of reach of private individuals and heavily regulated. The population density of LBZ is just 14-15 people per acre while other parts of Delhi are starved for space with density as high as 1,100 to 1,600 people per acre.</strong> <a href="https://wiki.dhanvapasi.com/index.php/Lutyens_Bungalow_Zone#cite_note-1">[1]</a></p>
<p><strong>Land allotment and its utilisation is highly arbitrary and discretionary on the government officials. There is an absence of a uniform rental policy in place for political groups that occupy the majority of the 25 sq. km area.</strong><br>
In their replies to RTI petitions, urban authorities have compounded the riddle that how sprawling Lutyens’ estates under government control are allocated.<br>
An RTI filed with the authorities found out that the rules of the urban development ministry have been generously relaxed for the Congress and the BJP, India’s two big parties. In 2015, the Congress was served a government notice to vacate all four addresses. In fact, their allotment was also cancelled. Yet, the party remains in possession of all the estates. On paper, every national party is entitled to run an office on government land in Delhi for three years. After that, they are required to shift their work-place to privately-owned space.</p>
<p>National presidents of designated national political parties qualify for residential accommodation in Delhi only if they don’t have any other in any other capacity. The BJP has two bungalows in its possession in Lutyens’ Delhi: 11, Ashoka Road, its former party headquarter and 14, Pt. Pant Marg, office of the party’s state unit. Two different RTI responses by the directorate of estates give two different rentals for 11 Ashok Road. The March reply quotes it at Rs 3,920 per month, the April note to as high as Rs 78,921 a month.</p>
<p>In another response from the government, the Congress is paying merely Rs 3,920 as monthly rent for 24, Akbar Road. While the Chanakyapuri bungalow under the occupancy of NCP is used as the residence of party office-bearers.<br>
As per a government circular of July 31, 2014 no state party is entitled to office space on government estate. However, the NCP, BSP, Samajwadi Party also have their offices in government-provided accommodation. <a href="https://wiki.dhanvapasi.com/index.php/Lutyens_Bungalow_Zone#cite_note-2">[2]</a></p>
<p>According to an official at DDA “At the core of the LBZ, there are many ‘loose’ areas, including triangular blocks, barracks, and quarters where proper utilisation of land and densification is possible.<br>
The valuation of the 25 sq. km parcel is valued conservatively (u[s]ing FSI of only 1) at ₹ 19.32 lakh crore. <a href="https://wiki.dhanvapasi.com/index.php/Lutyens_Bungalow_Zone#cite_note-3">[3]</a></p>
<img src="https://substackcdn.com/image/fetch/w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F60f4e084-bbc1-4193-9664-b0dbbeda4ffc_992x744.png" title="https://wiki.dhanvapasi.com/images/9/96/LBZ_final.png" class="img-fluid" alt="https://wiki.dhanvapasi.com/images/9/96/LBZ_final.png">
<p>References</p>
<ol type="1">
<li><p><a href="https://www.hindustantimes.com/delhi-news/delhi-real-estate-boom-coming-as-lutyens-zone-set-to-shrink/story-u2bccMQBpBrxYXjteuIw0M.html">“HT”</a></p></li>
<li><p><a href="https://www.indiatoday.in/india/story/rti-reveals-bjp-congress-hold-lion-s-share-in-lutyens-bungalow-zone-1245307-2018-05-29">“India Today”</a></p></li>
<li><p>[Calculation - Total Area x Circle Rate] - 2,49,70,075.05 sq.metre (6,170.24 acre) x ₹ 7.74 lakh/sq.metre = ₹ 19.32 lak crore.</p></li>
</ol>
</blockquote>
<p><a href="https://wiki.dhanvapasi.com/index.php/Lutyens_Bungalow_Zone">source</a> (emphasis mine)</p>
<p>If we lease all this land and collect rent on it, then using their valuation of Rs. 19.32 lakh crore (which is based on the assumption of FSI of 1 and circle rate of Rs. 7.74 lakh per square meter) and a rent rate of 2%, the rent proceeds from all this land will be ~Rs. 38,640 crore per year. If this rent is distributed amongst all adult citizens of India, then each will receive ~Rs. 386 per year; if it is distributed amongst all adult citizens of Delhi, then each will receive ~Rs. 26,648 per year.</p>
</section>
<section id="the-cheap-leashold-of-igi-airport" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="the-cheap-leashold-of-igi-airport"><span class="header-section-number">3</span> The cheap leashold of IGI Airport</h2>
<p><img src="https://substackcdn.com/image/fetch/w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F95c3121e-cab1-40e7-ade9-3b717c0c790c_2758x1378.png" class="img-fluid"></p>
<p><a href="https://earth.google.com/web/@28.56054548,77.09065125,244.36215027a,16937.85140459d,35y,244.90406667h,0t,0r">source</a>: An imperfect perimeter of IGI Airport on Google Earth. The actual area is ~4800 acres (i.e.&nbsp;~244 acres less than the area within the perimeter I drew).</p>
<blockquote class="blockquote">
<p>The Comptroller and Auditor General (CAG) has unearthed a whopping Rs 1.63 lakh crore scam related to the Delhi airport land deal.</p>
<p><strong>According to the CAG report, the government gave 4,799.09 acre of prime land on lease to its private sector partner Delhi International Airport Limited (DIAL) for development of the airport. The land was given on a paltry lease rent of Rs 100 per acre per year for a period of 60 years.</strong></p>
<p><strong>Interestingly, DIAL itself has estimated that commercial exploitation of the land for 60 years would give it profit to the tune of Rs 1.63 lakh crore.</strong></p>
<p>In its report, the CAG has indicted the Union civil aviation ministry’s role in land allocation in a number of places. It clearly states that “the ministry and the AAI (Airports Authority of India) have always ruled in favour of the operators and against the interest of the government”.</p>
<p>The loot did not stop at highly discounted lease rent. Despite that unfair advantage, DIAL went a step further and got a post-contractual benefit of levying airport development fees of Rs 1,300 extra for international flight and Rs 200 for domestic journey from each passenger.</p>
<p>DIAL also mints money from the 5 per cent land it has been allowed to use for commercial exploitation. Hotels, malls etc have been built on this land and DIAL gets a share of their profits.</p>
<p>Minister calls it ‘draft report’</p>
<p>Civil Aviation Minister Ajit Singh played it safe on the damning CAG report. He said it was just a “draft report”.</p>
<p>“It is a draft report. We will cooperate. Let us not level any allegations. We should wait for the final report,” the minister said.</p>
</blockquote>
<p><a href="https://www.indiatoday.in/india/north/story/delhi-airport-land-deal-scam-cag-aviation-ministry-103088-2012-05-22">source</a> (emphasis mine)</p>
<p>I have not been alble to find any reporting of a follow-up after this CAG report. I guess if the lease was shorter (like 5-10 years) and the rent was as per market rate, it would have been able to generate much more rent but even if we take the figure provided by CAG (i.e.&nbsp;Rs. 1.63 lakh crore for 60 years), the rent proceeds from this land parcel will be ~Rs. 2,716 crore per year. If this rent is distributed amongst all adult citizens of India, then each will receive ~Rs. 27 per year; if it is distributed amongst all adult citizens of Delhi, then each will receive ~1,874 per year.</p>
</section>
<section id="the-rent-free-jawaharlal-nehru-university" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="the-rent-free-jawaharlal-nehru-university"><span class="header-section-number">4</span> The rent-free Jawaharlal Nehru University</h2>
<p>One other <em>interesting</em> (yes, I couldn’t figure out a better word) parcel of land that sits in the middle of Delhi is the campus of Jawaharlal Nehru University.</p>
<p><img src="https://substackcdn.com/image/fetch/w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F43c30ecb-c62f-4837-af88-edfdc5531b81_2764x1382.png" class="img-fluid"></p>
<p><a href="https://earth.google.com/web/@28.54009362,77.16603759,283.49414867a,5693.74416144d,35y,10.56465362h,0t,0r">source</a>: An imperfect perimeter of JNU on Google Earth. The actual area is ~1000 acres (i.e.&nbsp;~64 acres more than the area within the perimeter I drew). For reference, you can look at <a href="https://images.app.goo.gl/hiBY4VXryr4Pfchv5">this (click)</a>.</p>
<p>The entire campus of JNU is spread across 1000 acres overlooking a slum on Nelson Mandela Marg (north of the campus) and other congested housing surrounding the campus. It borders the localities in the <a href="https://www.magicbricks.com/blog/circle-rates-in-delhi/118402.html">circle-rate categories B and C</a> (Hauz Khas, Vasant Kunj, Munirka, etc) which means that considering an average value of Rs. 2,00,000 per square meter is reasonable. If we consider a rent rate of 2%, the rent proceeds from this land parcel will be ~Rs. 1,618 crore per year. If this rent is distributed amongst all adult citizens of India, then each will receive ~Rs. 16 per year; if it is distributed amongst all adult citizens of Delhi, then each will receive ~1,116 per year.</p>
<script src="https://utteranc.es/client.js" repo="vinamrsachdeva/vinamrsachdeva.github.io" issue-term="pathname" label="comments" theme="github-light" crossorigin="anonymous" async="">
</script>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>